@extends('layouts.app')

@section('content')
<section class="bg-white border-bottom"><div class="container section-space"><div class="row align-items-center g-5"><div class="col-lg-7" data-aos="fade-up"><div class="section-kicker mb-3">Portal informasi lingkungan</div><h1 class="display-5 fw-bold lh-sm mb-3">{{ $profile->name ?? 'RW 012' }}</h1><p class="fs-5 text-secondary mb-4">{{ $profile->village ?? 'Kelurahan Bugel' }}, {{ $profile->district ?? 'Kecamatan Karawaci' }}, {{ $profile->city ?? 'Kota Tangerang' }}</p><p class="text-secondary col-lg-10">Informasi kegiatan, pengumuman, dan layanan lingkungan yang dapat diakses warga dengan mudah.</p><div class="d-flex flex-wrap gap-2 mt-4"><a href="{{ route('pengumuman') }}" class="btn btn-primary">Lihat pengumuman</a><a href="{{ route('profil') }}" class="btn btn-outline-primary">Mengenal RW 012</a></div></div><div class="col-lg-5 text-center" data-aos="fade-up" data-aos-delay="80"><img src="{{ asset('assets/images/rw012.jpeg') }}" alt="Logo RW 012" class="img-fluid" style="width:190px;max-height:190px;object-fit:cover;border:1px solid var(--rw-line);padding:7px;border-radius:50%;"><div class="small text-secondary mt-3">Melayani dan menghubungkan warga</div></div></div></div></section>

<section class="bg-white border-bottom"><div class="container"><div class="row g-0"><div class="col-6 col-lg-3 p-4 border-start border-end border-bottom"><div class="text-secondary small">Total warga</div><strong class="fs-2">{{ $totalWarga ?: 0 }}</strong></div><div class="col-6 col-lg-3 p-4 border-end border-bottom"><div class="text-secondary small">Rukun tetangga</div><strong class="fs-2">{{ $rts->count() }}</strong><span class="small text-secondary ms-1">RT</span></div><div class="col-6 col-lg-3 p-4 border-end"><div class="text-secondary small">Kegiatan terjadwal</div><strong class="fs-2">{{ $events->count() }}</strong></div><div class="col-6 col-lg-3 p-4 border-end"><div class="text-secondary small">Pengumuman aktif</div><strong class="fs-2">{{ $announcements->count() }}</strong></div></div></div></section>

<section class="section-space"><div class="container"><div class="row g-5"><div class="col-lg-6" data-aos="fade-up"><div class="d-flex justify-content-between align-items-end mb-3"><div><div class="section-kicker">Informasi warga</div><h2 class="section-title mb-0">Pengumuman terbaru</h2></div><a href="{{ route('pengumuman') }}" class="small">Lihat semua</a></div>@forelse($announcements as $announcement)<article class="content-panel p-3 mb-2"><div class="d-flex justify-content-between gap-2"><small class="text-secondary">{{ $announcement->publish_date ? \Carbon\Carbon::parse($announcement->publish_date)->format('d M Y') : $announcement->created_at->format('d M Y') }}</small>@if($announcement->is_pinned)<span class="badge text-bg-warning">Penting</span>@endif</div><h3 class="h6 fw-bold mt-2 mb-1">{{ $announcement->title }}</h3><p class="small text-secondary mb-0">{{ Str::limit($announcement->content, 120) }}</p></article>@empty<div class="content-panel text-center text-secondary p-4">Belum ada pengumuman.</div>@endforelse</div>
<div class="col-lg-6" data-aos="fade-up" data-aos-delay="70"><div class="d-flex justify-content-between align-items-end mb-3"><div><div class="section-kicker">Laporan lingkungan</div><h2 class="section-title mb-0">Daily report</h2></div><a href="{{ route('daily-report') }}" class="small">Lihat semua</a></div>@forelse($reports as $report)<article class="content-panel p-3 mb-2"><div class="d-flex justify-content-between gap-2"><small class="text-secondary">{{ \Carbon\Carbon::parse($report->date)->format('d M Y') }}</small><span class="badge text-bg-light border">{{ $report->category }}</span></div><h3 class="h6 fw-bold mt-2 mb-1">{{ $report->title }}</h3><p class="small text-secondary mb-0">{{ Str::limit($report->description, 120) }}</p></article>@empty<div class="content-panel text-center text-secondary p-4">Belum ada daily report.</div>@endforelse</div></div></div></section>

<section class="section-space bg-white border-top border-bottom"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><div class="section-kicker">Agenda lingkungan</div><h2 class="section-title mb-0">Kegiatan terbaru</h2></div><a href="{{ route('kegiatan') }}" class="small">Semua kegiatan</a></div><div class="row g-3">@forelse($events as $event)<div class="col-md-4" data-aos="fade-up"><article class="card card-hover h-100 overflow-hidden">@if($event->photo_path)<img src="{{ asset('storage/' . $event->photo_path) }}" alt="{{ $event->title }}" style="height:190px;width:100%;object-fit:cover;">@endif<div class="card-body"><small class="text-secondary"><i class="bi bi-calendar3 me-1"></i>{{ \Carbon\Carbon::parse($event->event_date)->format('d M Y') }}</small><h3 class="h5 fw-bold mt-2">{{ $event->title }}</h3>@if($event->location)<p class="small text-secondary mb-2"><i class="bi bi-geo-alt me-1"></i>{{ $event->location }}</p>@endif<p class="small text-secondary mb-0">{{ Str::limit($event->description, 105) }}</p></div></article></div>@empty<div class="col-12"><div class="content-panel text-center text-secondary p-4">Belum ada kegiatan yang dijadwalkan.</div></div>@endforelse</div></div></section>

<section class="section-space"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><div class="section-kicker">Dokumentasi warga</div><h2 class="section-title mb-0">Galeri kegiatan</h2></div><a href="{{ route('galeri') }}" class="small">Buka galeri</a></div><div class="row g-3">@forelse($galleries as $gallery)<div class="col-6 col-md-3" data-aos="fade-up"><a href="{{ route('galeri') }}" class="d-block overflow-hidden card-hover" style="border-radius:.4rem"><img src="{{ asset('storage/' . $gallery->image_path) }}" alt="{{ $gallery->title }}" class="w-100" style="height:190px;object-fit:cover;transition:transform .25s ease" onmouseover="this.style.transform='scale(1.03)'" onmouseout="this.style.transform='scale(1)'"></a></div>@empty<div class="col-12"><div class="content-panel text-center text-secondary p-4">Dokumentasi kegiatan akan ditampilkan di sini.</div></div>@endforelse</div></div></section>

<section class="py-5" style="background:#145a8d"><div class="container text-center text-white" data-aos="fade-up"><h2 class="h3 fw-bold">Butuh bantuan atau informasi lebih lanjut?</h2><p class="mb-4 opacity-75">Hubungi layanan masyarakat RW 012.</p>@if($rwContact)<a href="https://wa.me/{{ preg_replace('/[^0-9]/', '', $rwContact->phone_number) }}" class="btn btn-light text-success"><i class="bi bi-whatsapp me-1"></i>{{ $rwContact->phone_number }}</a>@else<a href="{{ route('kontak') }}" class="btn btn-light text-primary">Hubungi kami</a>@endif</div></section>
@endsection
