@extends('layouts.app')

@section('content')
@php
    $hasRole = fn ($member, $keyword) => $member && str_contains(strtolower($member->role ?? ''), $keyword);
    $ketuaRw = $rwMembers->first(fn ($member) => $hasRole($member, 'ketua rw'))
        ?? $rwMembers->first(fn ($member) => $hasRole($member, 'ketua'));
    $sekretaris = $rwMembers->first(fn ($member) => $hasRole($member, 'sekretaris'));
    $bendahara = $rwMembers->first(fn ($member) => $hasRole($member, 'bendahara'));
    $coreIds = collect([$ketuaRw, $sekretaris, $bendahara])->filter()->pluck('id');
    $otherRwMembers = $rwMembers->reject(fn ($member) => $coreIds->contains($member->id));
@endphp
<style>
    .org-diagram{position:relative;max-width:1040px;margin:auto}.org-level{position:relative;display:flex;justify-content:center;gap:1rem}.org-level--staff{margin-top:2.8rem}.org-level--rt{margin-top:2.8rem}.org-level--staff::before,.org-level--rt::before{content:"";position:absolute;height:1.4rem;border-left:1px solid #aac0ce;top:-1.4rem}.org-level--staff::after,.org-level--rt::after{content:"";position:absolute;top:-1.4rem;width:50%;border-top:1px solid #aac0ce}.org-node{position:relative;width:100%;max-width:245px;background:#fff;border:1px solid var(--rw-line);border-radius:.45rem;padding:1rem;text-align:center;z-index:1}.org-node--primary{border-top:3px solid var(--rw-blue)}.org-node--rt{border-top:3px solid var(--rw-green)}.org-photo{width:58px;height:58px;object-fit:cover;border-radius:50%;border:1px solid var(--rw-line);padding:2px}.org-placeholder{width:58px;height:58px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;background:#f1f5f7;border:1px solid var(--rw-line);color:#647381;font-size:1.5rem}.org-role{font-size:.76rem;font-weight:700;text-transform:uppercase;letter-spacing:.045em;color:var(--rw-green)}.org-name{font-size:.98rem;font-weight:700;margin:.4rem 0 .05rem}.org-note{font-size:.8rem;color:#74818a}.rt-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;width:100%}.member-list{border-top:1px solid var(--rw-line);margin-top:.65rem;padding-top:.65rem;text-align:left}.member-list li{font-size:.82rem;padding:.25rem 0;border-bottom:1px solid #edf1f3}.member-list li:last-child{border-bottom:0}@media(max-width:767.98px){.org-level{flex-direction:column;align-items:center}.org-level--staff,.org-level--rt{margin-top:1.25rem}.org-level--staff::before,.org-level--staff::after,.org-level--rt::before,.org-level--rt::after{display:none}.rt-grid{grid-template-columns:1fr}.org-node{max-width:360px}.org-level--staff .org-node{max-width:360px}}
</style>
<div class="container section-space">
    <div class="text-center mx-auto mb-5" style="max-width:650px" data-aos="fade-up"><div class="section-kicker mb-2">Kepengurusan lingkungan</div><h1 class="section-title mb-2">Struktur Organisasi RW 012</h1><p class="text-secondary mb-0">Susunan pengurus RW dan RT yang aktif melayani warga.</p></div>

    <section class="content-panel p-3 p-md-5" data-aos="fade-up"><div class="mb-4"><h2 class="h5 fw-bold mb-0">Struktur Kepengurusan RW 012</h2><p class="small text-secondary mb-0">Ketua RW, staf inti, dan pengurus RT 001–003</p></div><div class="org-diagram">
        <div class="org-level"><article class="org-node org-node--primary">@if($ketuaRw?->photo_path)<img class="org-photo" src="{{ asset('storage/' . $ketuaRw->photo_path) }}" alt="{{ $ketuaRw->name }}">@else<div class="org-placeholder"><i class="bi bi-person"></i></div>@endif<div class="org-role">Ketua RW</div><div class="org-name">{{ $ketuaRw->name ?? 'Belum ditetapkan' }}</div>@if($ketuaRw?->period)<div class="org-note">Periode {{ $ketuaRw->period }}</div>@endif</article></div>
        <div class="org-level org-level--staff"><article class="org-node">@if($sekretaris?->photo_path)<img class="org-photo" src="{{ asset('storage/' . $sekretaris->photo_path) }}" alt="{{ $sekretaris->name }}">@else<div class="org-placeholder"><i class="bi bi-person"></i></div>@endif<div class="org-role">Sekretaris</div><div class="org-name">{{ $sekretaris->name ?? 'Belum ditetapkan' }}</div>@if($sekretaris?->period)<div class="org-note">Periode {{ $sekretaris->period }}</div>@endif</article><article class="org-node">@if($bendahara?->photo_path)<img class="org-photo" src="{{ asset('storage/' . $bendahara->photo_path) }}" alt="{{ $bendahara->name }}">@else<div class="org-placeholder"><i class="bi bi-person"></i></div>@endif<div class="org-role">Bendahara</div><div class="org-name">{{ $bendahara->name ?? 'Belum ditetapkan' }}</div>@if($bendahara?->period)<div class="org-note">Periode {{ $bendahara->period }}</div>@endif</article></div>
        <div class="org-level org-level--rt"><div class="rt-grid">@forelse($rts as $rt)@php $members = $rtMembers->where('rt_id', $rt->id); $ketuaRt = $members->first(fn ($member) => $hasRole($member, 'ketua')) ?? $members->first(); $rtStaff = $members->reject(fn ($member) => $ketuaRt && $member->id === $ketuaRt->id); $rtLabel = str_starts_with(strtolower($rt->name), 'rt') ? $rt->name : 'RT ' . $rt->name; @endphp<article class="org-node org-node--rt">@if($ketuaRt?->photo_path)<img class="org-photo" src="{{ asset('storage/' . $ketuaRt->photo_path) }}" alt="{{ $ketuaRt->name }}">@else<div class="org-placeholder"><i class="bi bi-person"></i></div>@endif<div class="org-role">{{ $ketuaRt->role ?? 'Pengurus ' . $rtLabel }}</div><div class="org-name">{{ $ketuaRt->name ?? 'Belum ada data pengurus' }}</div>@if($ketuaRt?->period)<div class="org-note">Periode {{ $ketuaRt->period }}</div>@endif @if($rtStaff->isNotEmpty())<ul class="member-list list-unstyled mb-0"><li class="fw-semibold text-secondary">Anggota pengurus {{ $rtLabel }}</li>@foreach($rtStaff as $member)<li><span class="fw-semibold">{{ $member->name }}</span><br><span class="text-secondary">{{ $member->role }}</span></li>@endforeach</ul>@endif</article>@empty<div class="text-center text-secondary py-3">Data RT belum tersedia.</div>@endforelse</div></div>
    </div></section>

    @if($otherRwMembers->isNotEmpty())<section class="mt-5" data-aos="fade-up"><h2 class="h5 fw-bold mb-3">Anggota pengurus RW</h2><div class="row g-3">@foreach($otherRwMembers as $member)<div class="col-12 col-sm-6 col-lg-4"><article class="content-panel p-3 d-flex align-items-center gap-3">@if($member->photo_path)<img src="{{ asset('storage/' . $member->photo_path) }}" alt="{{ $member->name }}" class="rounded-circle" style="width:52px;height:52px;object-fit:cover">@else<div class="org-placeholder flex-shrink-0" style="width:52px;height:52px"><i class="bi bi-person"></i></div>@endif<div><h3 class="h6 fw-bold mb-1">{{ $member->name }}</h3><p class="small text-accent fw-semibold mb-0">{{ $member->role }}</p></div></article></div>@endforeach</div></section>@endif

    @if($karangTarunaMembers->isNotEmpty())<section class="mt-5" data-aos="fade-up"><h2 class="h5 fw-bold mb-3">Karang Taruna</h2><div class="row g-3">@foreach($karangTarunaMembers as $member)<div class="col-12 col-sm-6 col-lg-4"><article class="content-panel p-3 d-flex align-items-center gap-3">@if($member->photo_path)<img src="{{ asset('storage/' . $member->photo_path) }}" alt="{{ $member->name }}" class="rounded-circle" style="width:52px;height:52px;object-fit:cover">@else<div class="org-placeholder flex-shrink-0" style="width:52px;height:52px"><i class="bi bi-person"></i></div>@endif<div><h3 class="h6 fw-bold mb-1">{{ $member->name }}</h3><p class="small text-secondary fw-semibold mb-0">{{ $member->role }}</p></div></article></div>@endforeach</div></section>@endif
</div>
@endsection
