<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RW 012 - Portal Informasi Lingkungan</title><meta name="description" content="Portal informasi digital RW 012, Kelurahan Bugel, Kecamatan Karawaci, Kota Tangerang.">
    <link rel="icon" href="{{ asset('favicon.ico') }}"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <style>
        :root{--rw-blue:#145a8d;--rw-blue-dark:#0d4169;--rw-green:#27835c;--rw-ink:#1e2b36;--rw-muted:#647381;--rw-surface:#f5f7f8;--rw-line:#dce3e7}html{scroll-behavior:smooth}body{font-family:Inter,"Segoe UI",Arial,sans-serif;color:var(--rw-ink);background:var(--rw-surface);line-height:1.6}main{min-height:60vh}.navbar{background:#fff!important;border-bottom:1px solid rgba(20,90,141,.13);padding:.7rem 0;transition:box-shadow .2s ease}.navbar.scrolled{box-shadow:0 3px 14px rgba(29,52,67,.09)}.navbar-brand{color:var(--rw-blue)!important;font-size:1rem;letter-spacing:.02em}.brand-mark{width:38px;height:38px;object-fit:cover;border:1px solid var(--rw-line);border-radius:50%;padding:2px}.nav-link{color:#43525d!important;font-size:.9rem;font-weight:600;padding:.55rem .7rem!important}.nav-link:hover,.nav-link.active{color:var(--rw-blue)!important}.nav-link.active{box-shadow:inset 0 -2px 0 var(--rw-blue)}.dropdown-menu{border:1px solid var(--rw-line);border-radius:.45rem;box-shadow:0 8px 20px rgba(29,52,67,.1);padding:.4rem}.dropdown-item{border-radius:.25rem;font-size:.9rem;padding:.5rem .7rem}.dropdown-item:hover{color:var(--rw-blue);background:#edf5f9}.btn{border-radius:.35rem;font-weight:600;padding:.55rem 1rem;transition:transform .18s ease,background-color .18s ease}.btn:hover{transform:translateY(-1px)}.btn-primary{background:var(--rw-blue);border-color:var(--rw-blue)}.btn-primary:hover{background:var(--rw-blue-dark);border-color:var(--rw-blue-dark)}.btn-success{background:var(--rw-green);border-color:var(--rw-green)}.section-space{padding:5rem 0}.section-kicker{color:var(--rw-green);font-size:.76rem;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.section-title{font-size:clamp(1.6rem,3vw,2.2rem);font-weight:700;letter-spacing:-.025em}.content-panel{background:#fff;border:1px solid var(--rw-line);border-radius:.45rem}.card{border:1px solid var(--rw-line);border-radius:.45rem;box-shadow:none}.card-hover{transition:transform .2s ease,border-color .2s ease,box-shadow .2s ease}.card-hover:hover{transform:translateY(-3px);border-color:#b7cfdd;box-shadow:0 8px 18px rgba(29,52,67,.07)}main h1>i,main h2>i,main h3>i{display:none}.shadow,.shadow-sm{box-shadow:none!important}.text-accent{color:var(--rw-green)!important}.badge{border-radius:.25rem;font-weight:600;padding:.4em .6em}.form-control,.form-select{border-color:#cfd9df;border-radius:.35rem;padding:.6rem .75rem}.form-control:focus,.form-select:focus{border-color:#79a8c4;box-shadow:0 0 0 .2rem rgba(20,90,141,.12)}footer{background:#183344;color:#c5d0d5}footer h5{font-size:.95rem}footer a{color:#c5d0d5;text-decoration:none}footer a:hover{color:#fff}@media(max-width:991.98px){.navbar-collapse{padding:1rem 0 .35rem}.nav-link.active{box-shadow:inset 3px 0 0 var(--rw-blue)}.section-space{padding:3.5rem 0}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,::before,::after{transition-duration:.01ms!important;animation-duration:.01ms!important}}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg sticky-top" id="siteNav"><div class="container"><a class="navbar-brand d-flex align-items-center fw-bold" href="{{ route('home') }}"><img src="{{ asset('assets/images/rw012.jpeg') }}" alt="Logo RW 012" class="brand-mark me-2">RW 012 <span class="fw-normal text-secondary ms-1">| Bugel</span></a><button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-label="Buka navigasi"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto align-items-lg-center"><li class="nav-item"><a class="nav-link {{ request()->routeIs('home') ? 'active' : '' }}" href="{{ route('home') }}">Beranda</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('profil') ? 'active' : '' }}" href="{{ route('profil') }}">Profil</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('peta','struktur') ? 'active' : '' }}" href="{{ route('peta') }}">Wilayah</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle {{ request()->routeIs('daily-report','pengumuman','data-warga','rt','karang-taruna') ? 'active' : '' }}" href="#" data-bs-toggle="dropdown">Informasi</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="{{ route('pengumuman') }}">Pengumuman</a></li><li><a class="dropdown-item" href="{{ route('daily-report') }}">Daily report</a></li><li><a class="dropdown-item" href="{{ route('data-warga') }}">Data warga</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="{{ route('struktur') }}">Struktur pengurus</a></li><li><a class="dropdown-item" href="{{ route('karang-taruna') }}">Karang taruna</a></li></ul></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('kegiatan') ? 'active' : '' }}" href="{{ route('kegiatan') }}">Kegiatan</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('galeri') ? 'active' : '' }}" href="{{ route('galeri') }}">Galeri</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('kontak','aspirasi') ? 'active' : '' }}" href="{{ route('kontak') }}">Kontak</a></li><li class="nav-item ms-lg-3 mt-2 mt-lg-0"><a class="btn btn-sm {{ auth()->check() ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ auth()->check() ? route('admin.index') : route('login') }}">{{ auth()->check() ? 'Admin' : 'Login' }}</a></li></ul></div></div></nav>
    <main>@yield('content')</main>
    <footer class="pt-5 pb-3"><div class="container"><div class="row gy-4"><div class="col-md-5"><div class="d-flex align-items-center text-white fw-bold mb-2"><img src="{{ asset('assets/images/rw012.jpeg') }}" alt="Logo RW 012" class="brand-mark me-2">RW 012 Kelurahan Bugel</div><p class="small mb-0">Pusat informasi dan layanan lingkungan untuk warga RW 012.</p></div><div class="col-6 col-md-3"><h5 class="text-white mb-3">Informasi</h5><ul class="list-unstyled small lh-lg mb-0"><li><a href="{{ route('pengumuman') }}">Pengumuman</a></li><li><a href="{{ route('kegiatan') }}">Kegiatan</a></li><li><a href="{{ route('galeri') }}">Galeri warga</a></li></ul></div><div class="col-6 col-md-4"><h5 class="text-white mb-3">Layanan Warga</h5><a class="small" href="{{ route('aspirasi') }}">Sampaikan aspirasi</a></div></div><div class="border-top border-secondary mt-4 pt-3 small">&copy; {{ date('Y') }} RW 012. Portal informasi lingkungan.</div></div></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script><script>AOS.init({duration:450,once:true,offset:60,disable:window.matchMedia('(prefers-reduced-motion: reduce)').matches});window.addEventListener('scroll',()=>document.getElementById('siteNav').classList.toggle('scrolled',scrollY>8),{passive:true});</script>
</body></html>
